### ISSUE TITLE
ListMachineFirewallRules fails on any container with a '*' in a tag value

### ISSUE THREAD

**Issue by KrisShannon** [joyent/sdc-fwapi#2]
I think there needs to be some kind of escaping in [`ruleMorayFilter`](https://github.com/joyent/sdc-fwapi/blob/62b46bb1a77a4fe800f99d2531944664a722abfa/lib/ufds/filter.js#L177).

I originally encountered this running `docker-compose up -d` from the ['WordPress on Autopilot' blog post](https://www.joyent.com/blog/wordpress-on-autopilot#basic-setup)

It was setting a label called `docker:label:com.docker.swarm.affinities` to a value of `["container!=~*"]` which was causing subsequent failures:

>    DockerError: problem loading containers; caused by InternalServerError: 
>    {"message":"fwapi_rules does not have indexes that support (fromtags=docker:label:com.docker.swarm.affinities=[\"container!=~*\"]=40)"}

**Comment by KrisShannon** [comment]
Just for reference:

>    `% docker --version`
>    `Docker version 1.9.1, build a34a1d5`
>    `% docker-compose --version`
>    `docker-compose version 1.5.2, build 7240ff3`

>    `[root@headnode (syd-1) ~]# sdcadm insts -o alias,version | sed -n -e /docker/p -e /moray/p -e /fwapi/p`
>    `docker0     release-20160818-20160818T182620Z-g72f456f`
>    `fwapi0      release-20160818-20160818T182700Z-g62b46bb`
>    `moray1      release-20160818-20160818T183706Z-ga13d20b`
>    `moray2      release-20160818-20160818T183706Z-ga13d20b`
>    `moray0      release-20160818-20160818T183706Z-ga13d20b`

**Comment by KrisShannon** [comment]
Well,  this is unfortunate.

The version of `ldap-filter` used by moray is 0.2.0 which parses escaping as backslash followed by the escaped character,  whereas the LDAP RFC's and newer versions of `ldap-filter` use a backslash followed by 2 hex-digits.

There are also other parsing bugs fixed with the newer version of `ldap-filter` (e.g. if the label contains the any of the strings `~=`, `>=`, `<=`, `:=`, `(`, `)` or ends with any of the characters `~`, `>`, `<`, `:` then similar failures to the `*` problem are likely)

It would be possible without too much effort to precede all instances of `*`, `(`, `)`, and `=` in a label value in the `ruleMorayFilter` function (also need to change the format string from `'(fromtags=%s=%s=%d)'` to `'(fromtags=%s=%s\\=%d)'` to protect against a possible problematic last character in the label value)

This would cause a hard dependency against the current escaping behaviour in moray making an upgrade of `ldap-filter` much more difficult. OTOH, maybe there is lots of knowledge of this incorrect escaping in other parts of Triton already...

**Comment by tgross** [comment]
@KrisShannon while I'll leave the discussion of whether this is a problem with fwapi up to the experts like @melloc I regularly test applications with Compose, but the label my more recent version of Compose sets is very different from yours.

I get the following when running that project on Triton Cloud:

```
$ docker-compose -version
docker-compose version 1.8.0, build f3628c7

$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep 15 11:20:26 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   node0.10.46
 Git commit:   8dd03e9
 Built:        Thu Aug  4 18:27:55 2016
 OS/Arch:      solaris/i386

$ docker inspect wp_wordpress_1  | json -a .Config.Labels
{
  "com.docker.compose.service": "wordpress",
  "com.docker.compose.config-hash": "...",
  "com.docker.compose.project": "consul",
  "com.docker.compose.version": "1.8.0",
  "com.docker.swarm.affinities": "[\"container!=~*wordpress*\"]",
  "com.docker.compose.oneoff": "False",
  "com.docker.compose.container-number": "1",
  "com.joyent.package": "g4-highcpu-1G"
}
```

**Comment by melloc** [comment]
@KrisShannon Sorry for the trouble, and thanks for reporting this! I've looked into the issue, and it is unfortunate. After talking with @pfmooney , we've concluded that the best thing is to fork node-ldap-filter v0.3.x into a Moray-specific node-moray-filter which will generate the correct escape sequences. Once I have this ready, I'll switch FWAPI over to building its queries using the library, so that the `*` characters get escaped correctly.

This has managed to accidentally work in the past because, up until 3755c1f, FWAPI used UFDS as its default backend, and UFDS allowed wildcard searches on that field.

**Comment by KrisShannon** [comment]
@melloc That's sounds like a reasonable solution to me. Are you also going to switch moray from ldap-filter to this fork?

The v0.3.x branch of node-ldap-filter no longer mis-parses an equality condition with a value that contains another filtertype (e.g. "(attr=a<=b)" is currently parsed by the v0.2.x branch as attribute "attr=a" <= value "b")

Do you think it would be a good idea to also escape the '=' character?  This would work-around this mis-parsing by the current (and older) versions of moray.

**Comment by KrisShannon** [comment]
@tgross Actually the label is the same as yours.

The specific container that set the `docker:label:com.docker.swarm.affinities` label to a value of `["container!=~*"]` was the `consul` container.  The dump you have from `docker inspect` has extra escaping of the quotes, but that's from the json syntax.  The actual value doesn't contain backslashes.

My output for the wordpress container is very similiar to yours:

```
$ docker inspect autopilotpatternwordpress_wordpress_1 | json -a .Config.Labels
{
  "com.docker.compose.service": "wordpress",
  "com.docker.compose.config-hash": "...",
  "com.docker.compose.project": "autopilotpatternwordpress",
  "com.docker.compose.version": "1.5.2",
  "com.docker.swarm.affinities": "[\"container!=~*wordpress*\"]",
  "com.docker.compose.oneoff": "False",
  "com.docker.compose.container-number": "1",
  "triton.cns.services": "wordpress",
  "com.joyent.package": "docker-1024"
}
```

**Comment by KrisShannon** [comment]
@melloc Sorry, I've just re-read the commit (joyent/node-moray-filter@2d71e81ab78) and saw you already included `=` in the characters to escape.

**Comment by melloc** [comment]
@KrisShannon I actually did it just last night, and wrote some more tests, after seeing your comment. :) I'm going to try running a bunch of them against the v0.2.x `ldap-filter` branch, to make sure that there aren't any other characters that need to be similarly escaped for older Morays.

**Comment by KrisShannon** [comment]
@melloc So I'm not going crazy...

I thought I had already looked at the new code and it was missing anything related to `=`

You must have `git commit --amend`ed and it seems github uses the author date (even though it uses the wording "USER committed X days ago")

**Comment by melloc** [comment]
Yes, it's related, but the last [part of the fix](https://cr.joyent.us/#/c/1042/) hasn't gone into FWAPI yet. That's blocking on another CR that supports it that should be done soon.

**Comment by melloc** [comment]
@KrisShannon With commit d31ccc0, this is now fixed. The next release will contain the fix. Sorry that this took a while to get in!
